# Generated by Django 3.0.6 on 2020-05-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Subject',
        ),
    ]
